const TEXT_COLOR = '#423f3b';
const PRIMARY_COLOR = '#cbbeb5';
const SECONDARY_COLOR = '#ffe5a9';
const HIGHLIGHT_COLOR = '#ff6666';
const DARK_BLUE = '#525266';

export { TEXT_COLOR, PRIMARY_COLOR, SECONDARY_COLOR, HIGHLIGHT_COLOR, DARK_BLUE };
